# Generated by Django 2.0.2 on 2019-05-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190526_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='image',
            new_name='slika',
        ),
    ]
